### ISSUE TITLE
V1.4 Final Deliverable todo list

### ISSUE THREAD

**Issue by SholihinK** [AY1920S1-CS2113T-W17-1/main#264]
Hey guys ! nm prepartion for v1.4 im gonna list the things needed since there's quite alot of task to complete!
To add along if there's anything next time.

Tick the below if your done with it. 

@jaedonkey 
 - [x] Fix edit bugs reported from PE  dry run
 - [x] Upload PPP (on Git, 2101 and 2113T submission folders) [TEAM_ID][Your Name]PPP.pdf
 - [x] Add logging
 - [x] Add Instructions for Manual Testing for edit & find
 - [x] Finalize UG & DG part.
 - [x] Junit test for own feature

@LTPZ 
 - [x] Fix help and deadline bugs reported from PE dry run
 - [x] Upload PPP (on Git, 2101 and 2113T submission folders) [TEAM_ID][Your Name]PPP.pdf
 - [x] Add logging
 - [x] Add Instructions for Manual Testing for help,deadline and recurring deadline.
 - [x] Finalize UG & DG part.
 - [x] Junit test for own feature

@yueyeah 
 - [x] Fix event bugs reported from PE dry run
 - [x] Upload PPP (on Git, 2101 and 2113T submission folders) [TEAM_ID][Your Name]PPP.pdf
 - [x] Add logging
 - [x] Add Instructions for Manual Testing for delete,event and recurring event.
 - [x] Finalize UG & DG part.
 - [x] Junit test for own feature

@Catherinetan99 
 - [x] Fix view-reminder & find-free time slot bugs reported from PE  dry run
 - [x] Upload PPP (on Git, 2101 and 2113T submission folders) [TEAM_ID][Your Name]PPP.pdf
 - [x] Add logging
 - [x] Add Instructions for Manual Testing for set-reminder,view-reminder & find-free time 
 - [x] Finalize UG & DG part.
 - [x] Junit test for own feature

@SholihinK  
 - [x] Fix view & list bugs reported from PE  dry run
 - [x] Upload PPP (on Git, 2101 and 2113T submission folders) [TEAM_ID][Your Name]PPP.pdf
 - [x] Add logging
 - [x] Add Instructions for Manual Testing for done,view,list,import and export
 - [x] Finalize UG & DG part.
 - [x] Junit test for own feature

Team misc
- [x] update readme.md on first page
- [x] upload jar v1.4 ,UG & DG on luminus
- [x] upload final UG & DG on github
